<<<<<<< Updated upstream
# Generated by Django 4.1.1 on 2022-10-03 10:16
=======
# Generated by Django 4.1.1 on 2022-10-03 06:47
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< Updated upstream
                ('image', models.ImageField(upload_to='images/')),
=======
                ('image', models.ImageField(upload_to='')),
>>>>>>> Stashed changes
            ],
            options={
                'db_table': 'tweet',
            },
        ),
    ]
